# Generated by Django 6.0.7 on 2026-07-21 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_placementcompany_placementround_placementresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leetcodechallenge',
            options={'ordering': ['available_date', 'day_number']},
        ),
        migrations.AddField(
            model_name='leetcodechallenge',
            name='available_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date when this problem unlocks'),
        ),
        migrations.AddField(
            model_name='leetcodechallenge',
            name='day_number',
            field=models.IntegerField(default=1, help_text='Day 1 to 10 designation'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last API activity', null=True),
        ),
        migrations.AlterField(
            model_name='leetcodechallenge',
            name='deadline',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='leetcodesubmission',
            index=models.Index(fields=['student', 'challenge'], name='api_leetcod_student_d2b57f_idx'),
        ),
    ]
