# Generated by Django 6.0.7 on 2026-07-21 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_leetcodechallenge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='max_seats',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='batch',
            name='trainer_name',
            field=models.CharField(blank=True, default='Senior Instructor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
