# Generated by Django 6.0.7 on 2026-07-24 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_passwordresetotp_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('github', 'GitHub Link'), ('written', 'Written Answer'), ('document', 'Document Upload')], default='written', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, upload_to='task_documents/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='written_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('specification_file', models.FileField(blank=True, null=True, upload_to='project_specifications/')),
                ('specification_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('specification_extracted_text', models.TextField(blank=True, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('maximum_marks', models.IntegerField(default=100)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.batch')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField()),
                ('deployment_url', models.URLField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project_match_score', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('obtained_marks', models.FloatField(blank=True, null=True)),
                ('evaluation_report', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('grading', 'Auto Grading...'), ('auto-graded', 'Auto-Graded'), ('admin-approved', 'Admin-Approved'), ('admin-overridden', 'Admin-Overridden'), ('review_required', 'Requires Admin Review')], default='pending', max_length=30)),
                ('admin_feedback', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'student')},
            },
        ),
    ]
